# tf.math.reduce_max
https://www.tensorflow.org/api_docs/python/tf/math/reduce_max

Computes tf.math.maximum of elements across dimensions of a tensor.

tf.math.reduce_max(
    input_tensor, axis=None, keepdims=False, name=None
)

Args
input_tensor 	The tensor to reduce. Should have real numeric type.
axis 	The dimensions to reduce. If None (the default), reduces all dimensions. Must be in the range [-rank(input_tensor), rank(input_tensor)).
keepdims 	If true, retains reduced dimensions with length 1.
name 	A name for the operation (optional).

Returns
The reduced tensor. 

In [1]:
import tensorflow as tf

In [2]:
x = tf.constant([5, 1, 2, 4])
tf.math.reduce_max(x)

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [3]:
x = tf.constant([-5, -1, -2, -4])
tf.reduce_max(x)

<tf.Tensor: shape=(), dtype=int32, numpy=-1>

In [6]:
x = tf.constant([4, float('nan')])
tf.reduce_max(x)

<tf.Tensor: shape=(), dtype=float32, numpy=nan>

In [7]:
x = tf.constant([float('nan'), float('nan')])
tf.reduce_max(x)

<tf.Tensor: shape=(), dtype=float32, numpy=nan>

In [8]:
x = tf.constant([float('-inf'), float('inf')])
tf.reduce_max(x)

<tf.Tensor: shape=(), dtype=float32, numpy=inf>

In [ ]:
# additional testing not related to this topic
x = tf.constant([-5, -1, -2, -4])
mask = (x < -2.0)
x[mask]

In [12]:
# additional testing not related to this topic
x = tf.constant([-5, -1, -2, -4])
mask = (x < -2.0)
x[mask]

TypeError: Cannot convert -2.0 to EagerTensor of dtype int32