#  tf.math.argmax
https://www.tensorflow.org/api_docs/python/tf/math/argmax

tf.math.argmax(
    input,
    axis=None,
    output_type=tf.dtypes.int64,
    name=None
)

Args: 
input 	A Tensor.
axis 	An integer, the axis to reduce across. Default to 0.
output_type 	An optional output dtype (tf.int32 or tf.int64). Defaults to tf.int64.
name 	An optional name for the operation. 

Returns: 
A Tensor of type output_type. 

In [1]:
import tensorflow as tf

In [4]:
A = tf.constant([2, 20, 30, 3, 6])
tf.math.argmax(A)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [5]:
B = tf.constant([[2, 20, 30, 3, 6], 
                 [3, 11, 16, 1, 8],
                 [14, 45, 23, 5, 27]
                ])
tf.math.argmax(B)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([2, 2, 0, 2, 2], dtype=int64)>

In [6]:
B = tf.constant([[2, 20, 30, 3, 6], 
                 [3, 11, 16, 1, 8],
                 [14, 45, 23, 5, 27]
                ])
tf.math.argmax(B, 0)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([2, 2, 0, 2, 2], dtype=int64)>

In [7]:
B = tf.constant([[2, 20, 30, 3, 6], 
                 [3, 11, 16, 1, 8],
                 [14, 45, 23, 5, 27]
                ])
tf.math.argmax(B, 1)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 2, 1], dtype=int64)>

In [8]:
C = tf.constant([0, 0, 0, 0])
tf.math.argmax(C)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [9]:
B = tf.constant([[2, 20, 30, 3, 6], 
                 [3, 11, 16, 1, 8],
                 [14, 45, 23, 5, 27]
                ])
tf.math.argmax(B, -1)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 2, 1], dtype=int64)>