# Tensor
https://www.coursera.org/learn/customising-models-tensorflow2/lecture/uOCx9/tensors

In [4]:
import tensorflow as tf

In [5]:
my_var = tf.Variable([-1, 2], dtype=tf.float32, name='my_var')
h = my_var + [5, 4]

print(h)

tf.Tensor([4. 6.], shape=(2,), dtype=float32)


In [2]:
import keras

In [3]:
inputs = keras.layers.Input(shape=(5,))
h = keras.layers.Dense(16, activation='sigmoid')(inputs)

print(h)

<KerasTensor shape=(None, 16), dtype=float32, sparse=False, name=keras_tensor_3>


In [1]:
from tensorflow.keras.layers import Dense, Input

inputs = Input(shape=(5,))
h = Dense(16, activation='sigmoid')(inputs)

print(h)

<KerasTensor shape=(None, 16), dtype=float32, sparse=False, name=keras_tensor_1>


In [9]:
from tensorflow.keras.layers import Dense, Input

inputs = Input(shape=(5,))
h = Dense(16, activation='sigmoid')(inputs)
outputs = Dense(10, activation='softmax')(h)

print(h)
print(outputs)

<KerasTensor shape=(None, 16), dtype=float32, sparse=False, name=keras_tensor_12>
<KerasTensor shape=(None, 10), dtype=float32, sparse=False, name=keras_tensor_13>


In [1]:
#from tensorflow.keras.layers import Dense, Input
#from tensorflow.keras.models import Model

import keras

inputs = keras.layers.Input(shape=(5,))
h = keras.layers.Dense(16, activation='sigmoid')(inputs)
outputs = keras.layers.Dense(10, activation='softmax')(h)

model = keras.models.Model(inputs=inputs, outputs=outputs)

print(model.input)
print(model.output)

<KerasTensor shape=(None, 5), dtype=float32, sparse=False, name=keras_tensor>
<KerasTensor shape=(None, 10), dtype=float32, sparse=False, name=keras_tensor_2>


In [2]:
import tensorflow as tf 

x = tf.constant([[5, 2], [1, 3]])
print(x)

tf.Tensor(
[[5 2]
 [1 3]], shape=(2, 2), dtype=int32)


In [5]:
import tensorflow as tf 

x = tf.constant([[5, 2], [1, 3]])
x_arr = x.numpy()
print(x_arr)

[[5 2]
 [1 3]]


In [6]:
import tensorflow as tf 

x = tf.ones(shape=(2, 1))
print(x)

y = tf.ones(shape=(2,1))
print(y)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


In [7]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Conv2D, AveragePooling2D, Flatten

inputs = Input(shape=(16, 16, 3))
h = Conv2D(32, 3, activation='relu')(inputs)
h = AveragePooling2D(3)(h)
outputs = Flatten()(h)
model = Model(inputs=inputs, outputs=outputs)
print(model.output)

<KerasTensor shape=(None, 512), dtype=float32, sparse=False, name=keras_tensor_6>
