# numpy.arange
https://numpy.org/doc/stable/reference/generated/numpy.arange.html

In [1]:
import numpy as np

numpy.arange([start, ]stop, [step, ]dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

arange can be called with a varying number of positional arguments:

    arange(stop): Values are generated within the half-open interval [0, stop) (in other words, the interval including start but excluding stop).

    arange(start, stop): Values are generated within the half-open interval [start, stop).

    arange(start, stop, step) Values are generated within the half-open interval [start, stop), with spacing between values given by step.

For integer arguments the function is roughly equivalent to the Python built-in range, but returns an ndarray rather than a range instance.

When using a non-integer step, such as 0.1, it is often better to use numpy.linspace.

See the Warning sections below for more information.

Parameters:

    startinteger or real, optional

        Start of interval. The interval includes this value. The default start value is 0.
    stopinteger or real

        End of interval. The interval does not include this value, except in some cases where step is not an integer and floating point round-off affects the length of out.
    stepinteger or real, optional

        Spacing between values. For any output out, this is the distance between two adjacent values, out[i+1] - out[i]. The default step size is 1. If step is specified as a position argument, start must also be given.
    dtypedtype, optional

        The type of the output array. If dtype is not given, infer the data type from the other input arguments.
    devicestr, optional

        The device on which to place the created array. Default: None. For Array-API interoperability only, so must be "cpu" if passed.

        New in version 2.0.0.
    likearray_like, optional

        Reference object to allow the creation of arrays which are not NumPy arrays. If an array-like passed in as like supports the __array_function__ protocol, the result will be defined by it. In this case, it ensures the creation of an array object compatible with that passed in via this argument.

        New in version 1.20.0.

Returns:

    arangendarray

        Array of evenly spaced values.

        For floating point arguments, the length of the result is ceil((stop - start)/step). Because of floating point overflow, this rule may result in the last element of out being greater than stop.



In [2]:
np.arange(3)

array([0, 1, 2])

In [3]:
np.arange(3, dtype=float)

array([0., 1., 2.])

In [4]:
np.arange(3,7)

array([3, 4, 5, 6])

In [5]:
np.arange(1, 7, dtype=float)

array([1., 2., 3., 4., 5., 6.])

### issues below, use npmy.linspaces

In [6]:
np.arange(0, 5, 0.5, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.arange(-3, 3, 0.5, dtype=int)

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])