# numpy.zeros
https://numpy.org/doc/stable/reference/generated/numpy.zeros.html#numpy-zeros

numpy.zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters:

    shapeint or tuple of ints

        Shape of the new array, e.g., (2, 3) or 2.
    dtypedata-type, optional

        The desired data-type for the array, e.g., numpy.int8. Default is numpy.float64.
    order{‘C’, ‘F’}, optional, default: ‘C’

        Whether to store multi-dimensional data in row-major (C-style) or column-major (Fortran-style) order in memory.
    likearray_like, optional

        Reference object to allow the creation of arrays which are not NumPy arrays. If an array-like passed in as like supports the __array_function__ protocol, the result will be defined by it. In this case, it ensures the creation of an array object compatible with that passed in via this argument.

        New in version 1.20.0.

Returns:

    out
    ndarray

        Array of zeros with the given shape, dtype, and order.

See also

zeros_like

    Return an array of zeros with shape and type of input.
empty

    Return a new uninitialized array.
ones

    Return a new array setting values to one.
full

    Return a new array of given shape filled with value.



In [3]:
import numpy as np

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [6]:
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

In [7]:
np.zeros((2, 1))

array([[0.],
       [0.]])

In [10]:
np.zeros((2,), dtype=[('x', 'i4'), ('y', 'i4')]) # custom dtype

array([(0, 0), (0, 0)], dtype=[('x', '<i4'), ('y', '<i4')])