# numpy.argmin
https://numpy.org/doc/stable/reference/generated/numpy.argmin.html#

numpy.argmin(a, axis=None, out=None, *, keepdims=<no value>)
[source]

Returns the indices of the minimum values along an axis.

Parameters:

    aarray_like

        Input array.
    axisint, optional

        By default, the index is into the flattened array, otherwise along the specified axis.
    outarray, optional

        If provided, the result will be inserted into this array. It should be of the appropriate shape and dtype.
    keepdimsbool, optional

        If this is set to True, the axes which are reduced are left in the result as dimensions with size one. With this option, the result will broadcast correctly against the array.

        New in version 1.22.0.

Returns:

    index_array
    ndarray of ints

        Array of indices into the array. It has the same shape as a.shape with the dimension along axis removed. If keepdims is set to True, then the size of axis will be 1 with the resulting array having same shape as a.shape.

See also

ndarray.argmin, argmax
amin

    The minimum value along a given axis.
unravel_index

    Convert a flat index into an index tuple.
take_along_axis

    Apply np.expand_dims(index_array, axis) from argmin to an array as if by calling min.



Notes

In case of multiple occurrences of the minimum values, the indices corresponding to the first occurrence are returned.

In [1]:
import numpy as np

In [2]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [3]:
a = a.reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [4]:
a = a + 10
a

array([[10, 11, 12],
       [13, 14, 15]])

In [5]:
np.argmin(a)

0