# numpy.random.randint
https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

numpy.random.randint
random.randint(low, high=None, size=None, dtype=int)

Return random integers from low (inclusive) to high (exclusive).

Return random integers from the “discrete uniform” distribution of the specified dtype in the “half-open” interval [low, high). If high is None (the default), then results are from [0, low).

Note

New code should use the integers method of a Generator instance instead; please see the Quick start.

Parameters:

    lowint or array-like of ints

        Lowest (signed) integers to be drawn from the distribution (unless high=None, in which case this parameter is one above the highest such integer).
    highint or array-like of ints, optional

        If provided, one above the largest (signed) integer to be drawn from the distribution (see above for behavior if high=None). If array-like, must contain integer values
    sizeint or tuple of ints, optional

        Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.
    dtypedtype, optional

        Desired dtype of the result. Byteorder must be native. The default value is long.

        Warning

        This function defaults to the C-long dtype, which is 32bit on windows and otherwise 64bit on 64bit platforms (and 32bit on 32bit ones). Since NumPy 2.0, NumPy’s default integer is 32bit on 32bit platforms and 64bit on 64bit platforms. Which corresponds to np.intp. (dtype=int is not the same as in most NumPy functions.)

Returns:

    out
    int or ndarray of ints

        size-shaped array of random integers from the appropriate distribution, or a single such random int if size not provided.

See also

random_integers

    similar to randint, only for the closed interval [low, high], and 1 is the lowest value if high is omitted.
random.Generator.integers

    which should be used for new code.



In [2]:
import numpy as np

In [2]:
np.random.randint(2, size=10)

array([1, 1, 1, 1, 0, 0, 1, 0, 0, 0])

In [3]:
np.random.randint(1, size=10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
np.random.randint(5, size=(2, 4))

array([[3, 0, 1, 1],
       [2, 1, 2, 3]])

In [5]:
np.random.randint(1, [3, 5, 10])

array([1, 4, 1])

In [6]:
np.random.randint([1, 5, 7], 10)

array([3, 7, 7])

In [7]:
np.random.randint([1, 3, 5, 7], [[10], [20]], dtype=np.uint8)

array([[ 5,  9,  6,  8],
       [10, 16, 12, 17]], dtype=uint8)

In [3]:
np.random.randint(1000, size=(32, 10))

array([[164, 464, 860, 603, 107, 714,  78,  89,  34, 905],
       [316, 164, 173, 147,  75, 351, 732, 598, 940, 247],
       [694, 272, 602, 499,  38, 542, 525, 786, 454, 733],
       [533, 719, 361, 513, 716,  53, 266, 831, 362, 740],
       [898, 544, 498, 201, 923,  58, 112, 786, 790, 252],
       [406, 838, 969, 172, 386, 639, 805, 734, 496, 744],
       [330, 690, 587, 514, 107, 553, 343, 132, 885, 356],
       [462, 995, 866, 282, 125, 780, 420, 976,  97, 497],
       [488, 636, 629, 114, 159, 480, 279, 331, 389, 972],
       [343, 696, 167, 569, 962, 247, 981, 642, 333, 286],
       [657, 242, 382, 820, 646, 242, 212, 809, 161, 173],
       [969, 304, 935, 633,   1, 951, 865, 363, 186, 783],
       [525, 435, 398, 525, 905, 936, 196, 632, 843, 414],
       [785, 655, 829,  41, 277,  21, 962, 441, 699,  13],
       [ 48, 134, 147, 766, 951, 654, 683, 678, 298, 297],
       [186, 354, 468, 177, 941, 241,  56, 223, 971, 358],
       [923, 235, 784, 127, 859, 897, 760, 204,  65, 806