# numpy.random.permutation
https://numpy.org/devdocs/reference/random/generated/numpy.random.permutation.html#numpy-random-permutation

random.permutation(x)

Randomly permute a sequence, or return a permuted range.

If x is a multi-dimensional array, it is only shuffled along its first index.

Note

New code should use the permutation method of a Generator instance instead; please see the Quick start.

Parameters:

    x
    int or array_like

        If x is an integer, randomly permute np.arange(x). If x is an array, make a copy and shuffle the elements randomly.

Returns:

    out
    ndarray

        Permuted sequence or array range.

See also

random.Generator.permutation

    which should be used for new code.



In [5]:
import numpy as np

np.random.seed(25)

In [12]:
# not seeded even called b4
np.random.permutation(10)

array([0, 8, 6, 5, 7, 1, 9, 3, 4, 2])

In [7]:
list(np.random.permutation(10))

[9, 2, 7, 8, 6, 0, 3, 1, 5, 4]

In [18]:
# seeded just b4 call permutation
np.random.seed(25)
np.random.permutation(10)

array([5, 1, 3, 8, 0, 2, 9, 7, 6, 4])

In [2]:
np.random.permutation([1, 4, 9, 12, 15])

array([ 1,  4, 12,  9, 15])

In [29]:
arr = np.arange(9).reshape((3, 3))

np.random.permutation(arr)

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [61]:
X = np.array([0.1, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.0])

np.random.seed(25)
p = np.random.permutation(10)
X = X[list(p)[0:2]]
X

array([5.5, 1.1])

In [54]:
X = np.array([[0.0, 1.1, 2.2, 3.3, 4.4], 
              [5.5, 6.6, 7.7, 8.8, 9.0]])

#np.random.seed(25)
p = list(np.random.permutation(2))
q = list(np.random.permutation(5))
print(p)
print(q)
X = X[p, :]
X

[0, 1]
[1, 4, 0, 2, 3]


array([[0. , 1.1, 2.2, 3.3, 4.4],
       [5.5, 6.6, 7.7, 8.8, 9. ]])