# tf.one_hot
https://www.tensorflow.org/api_docs/python/tf/one_hot

tf.one_hot(
    indices,
    depth,
    on_value=None,
    off_value=None,
    axis=None,
    dtype=None,
    name=None
)

Args
indices 	A Tensor of indices.
depth 	A scalar defining the depth of the one hot dimension.
on_value 	A scalar defining the value to fill in output when indices[j] = i. (default: 1)
off_value 	A scalar defining the value to fill in output when indices[j] != i. (default: 0)
axis 	The axis to fill (default: -1, a new inner-most axis).
dtype 	The data type of the output tensor.
name 	A name for the operation (optional).

Returns
output 	The one-hot tensor.

Raises
TypeError 	If dtype of either on_value or off_value don't match dtype
TypeError 	If dtype of on_value and off_value don't match one another 




See also tf.fill, tf.eye.

The locations represented by indices in indices take value on_value, while all other locations take value off_value.

on_value and off_value must have matching data types. If dtype is also provided, they must be the same data type as specified by dtype.

If on_value is not provided, it will default to the value 1 with type dtype

If off_value is not provided, it will default to the value 0 with type dtype

If the input indices is rank N, the output will have rank N+1. The new axis is created at dimension axis (default: the new axis is appended at the end).

If indices is a scalar the output shape will be a vector of length depth

If indices is a vector of length features, the output shape will be:

  features x depth if axis == -1
  depth x features if axis == 0

If indices is a matrix (batch) with shape [batch, features], the output shape will be:

  batch x features x depth if axis == -1
  batch x depth x features if axis == 1
  depth x batch x features if axis == 0

If indices is a RaggedTensor, the 'axis' argument must be positive and refer to a non-ragged axis. The output will be equivalent to applying 'one_hot' on the values of the RaggedTensor, and creating a new RaggedTensor from the result.

If dtype is not provided, it will attempt to assume the data type of on_value or off_value, if one or both are passed in. If none of on_value, off_value, or dtype are provided, dtype will default to the value tf.float32.

In [1]:
import tensorflow as tf

2025-03-21 08:58:20.048401: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-03-21 08:58:20.426510: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-03-21 08:58:24.711822: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-03-21 08:58:28.451833: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1742561911.705257  128161 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1742561912.54

In [2]:
indices = [0, 1, 2]
depth = 3
tf.one_hot(indices, depth)

2025-03-21 09:00:56.603182: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [3]:
indices = [0, 2, -1, 1]
depth = 3
tf.one_hot(indices, depth, on_value=5.0, off_value=0.0, axis=-1)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[5., 0., 0.],
       [0., 0., 5.],
       [0., 0., 0.],
       [0., 5., 0.]], dtype=float32)>

In [4]:
indices = [0, 2, -1, 1]
depth = 3
tf.one_hot(indices, depth, on_value=5.0, off_value=0.0, axis=0)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[5., 0., 0., 0.],
       [0., 0., 0., 5.],
       [0., 5., 0., 0.]], dtype=float32)>

In [5]:
indices = [[0, 2], [1, -1]]
depth = 3
tf.one_hot(indices, depth,
           on_value=1.0, off_value=0.0,
           axis=-1)

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[1., 0., 0.],
        [0., 0., 1.]],

       [[0., 1., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [6]:
indices = [[0, 2], [1, -1]]
depth = 3
tf.one_hot(indices, depth,
           on_value=1.0, off_value=0.0,
           axis=0)

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[1., 0.],
        [0., 0.]],

       [[0., 0.],
        [1., 0.]],

       [[0., 1.],
        [0., 0.]]], dtype=float32)>