# numpy.stack
https://numpy.org/doc/stable/reference/generated/numpy.stack.html#numpy-stack

numpy.stack(arrays, axis=0, out=None, *, dtype=None, casting='same_kind')
[source]

Join a sequence of arrays along a new axis.

The axis parameter specifies the index of the new axis in the dimensions of the result. For example, if axis=0 it will be the first dimension and if axis=-1 it will be the last dimension.

Parameters:

    arrayssequence of ndarrays

        Each array must have the same shape. In the case of a single ndarray array_like input, it will be treated as a sequence of arrays; i.e., each element along the zeroth axis is treated as a separate array.
    axisint, optional

        The axis in the result array along which the input arrays are stacked.
    outndarray, optional

        If provided, the destination to place the result. The shape must be correct, matching that of what stack would have returned if no out argument were specified.
    dtypestr or dtype

        If provided, the destination array will have this dtype. Cannot be provided together with out.

        New in version 1.24.
    casting{‘no’, ‘equiv’, ‘safe’, ‘same_kind’, ‘unsafe’}, optional

        Controls what kind of data casting may occur. Defaults to ‘same_kind’.

        New in version 1.24.

Returns:

    stacked
    ndarray

        The stacked array has one more dimension than the input arrays.

See also

concatenate

    Join a sequence of arrays along an existing axis.
block

    Assemble an nd-array from nested lists of blocks.
split

    Split array into a list of multiple sub-arrays of equal size.
unstack

    Split an array into a tuple of sub-arrays along an axis.



In [1]:
import numpy as np

In [3]:
rng = np.random.default_rng()
arrays = [rng.normal(size=(3,4)) for _ in range(10)]
arrays

[array([[ 1.0724265 , -1.4077657 ,  0.8154171 ,  0.22400859],
        [ 1.59208673, -0.15813458,  0.01523808,  1.47857232],
        [-0.23748143, -0.07471946, -1.23949728, -0.90760301]]),
 array([[-0.83734072,  0.90881973, -0.41690101, -0.67658573],
        [-1.18261647,  3.16273745,  0.99705485, -0.03175274],
        [-1.33011174,  0.59422455,  1.88893954,  1.24997471]]),
 array([[ 0.35038116,  0.07766091, -0.38447741, -0.05153722],
        [ 0.53524064,  0.03422265,  1.95069789, -0.31076241],
        [ 1.48398461, -0.25668927,  1.11624569, -2.28198563]]),
 array([[-0.25803833,  1.35064873, -2.84399124,  1.50910694],
        [-1.27412107, -1.12503984, -1.95106777, -0.43280349],
        [-0.60832399,  0.00526681,  2.49902313, -1.09825538]]),
 array([[-1.53303085,  0.51629969, -0.30762129,  1.46504408],
        [ 1.19152082,  1.07401234,  1.07896501, -0.39770001],
        [ 0.80776922,  2.18657845,  0.35455444,  1.20625613]]),
 array([[ 1.43994419,  1.72254078,  1.71281259,  0.62734512]

In [4]:
np.stack(arrays, axis=0)

array([[[ 1.0724265 , -1.4077657 ,  0.8154171 ,  0.22400859],
        [ 1.59208673, -0.15813458,  0.01523808,  1.47857232],
        [-0.23748143, -0.07471946, -1.23949728, -0.90760301]],

       [[-0.83734072,  0.90881973, -0.41690101, -0.67658573],
        [-1.18261647,  3.16273745,  0.99705485, -0.03175274],
        [-1.33011174,  0.59422455,  1.88893954,  1.24997471]],

       [[ 0.35038116,  0.07766091, -0.38447741, -0.05153722],
        [ 0.53524064,  0.03422265,  1.95069789, -0.31076241],
        [ 1.48398461, -0.25668927,  1.11624569, -2.28198563]],

       [[-0.25803833,  1.35064873, -2.84399124,  1.50910694],
        [-1.27412107, -1.12503984, -1.95106777, -0.43280349],
        [-0.60832399,  0.00526681,  2.49902313, -1.09825538]],

       [[-1.53303085,  0.51629969, -0.30762129,  1.46504408],
        [ 1.19152082,  1.07401234,  1.07896501, -0.39770001],
        [ 0.80776922,  2.18657845,  0.35455444,  1.20625613]],

       [[ 1.43994419,  1.72254078,  1.71281259,  0.62734512]

In [5]:
np.stack(arrays, axis=1)

array([[[ 1.0724265 , -1.4077657 ,  0.8154171 ,  0.22400859],
        [-0.83734072,  0.90881973, -0.41690101, -0.67658573],
        [ 0.35038116,  0.07766091, -0.38447741, -0.05153722],
        [-0.25803833,  1.35064873, -2.84399124,  1.50910694],
        [-1.53303085,  0.51629969, -0.30762129,  1.46504408],
        [ 1.43994419,  1.72254078,  1.71281259,  0.62734512],
        [-1.00185581, -1.0208297 , -0.67822744,  0.53674377],
        [ 1.60077993,  0.92342648,  0.2420977 , -0.31596875],
        [ 0.21553533, -1.08315018,  0.24314942,  0.5513387 ],
        [ 0.48033663, -0.47128308,  1.19097154, -0.43106991]],

       [[ 1.59208673, -0.15813458,  0.01523808,  1.47857232],
        [-1.18261647,  3.16273745,  0.99705485, -0.03175274],
        [ 0.53524064,  0.03422265,  1.95069789, -0.31076241],
        [-1.27412107, -1.12503984, -1.95106777, -0.43280349],
        [ 1.19152082,  1.07401234,  1.07896501, -0.39770001],
        [-0.04582379,  0.30729941, -0.17683123, -0.54781344],
      

In [6]:
np.stack(arrays, axis=2)

array([[[ 1.0724265 , -0.83734072,  0.35038116, -0.25803833,
         -1.53303085,  1.43994419, -1.00185581,  1.60077993,
          0.21553533,  0.48033663],
        [-1.4077657 ,  0.90881973,  0.07766091,  1.35064873,
          0.51629969,  1.72254078, -1.0208297 ,  0.92342648,
         -1.08315018, -0.47128308],
        [ 0.8154171 , -0.41690101, -0.38447741, -2.84399124,
         -0.30762129,  1.71281259, -0.67822744,  0.2420977 ,
          0.24314942,  1.19097154],
        [ 0.22400859, -0.67658573, -0.05153722,  1.50910694,
          1.46504408,  0.62734512,  0.53674377, -0.31596875,
          0.5513387 , -0.43106991]],

       [[ 1.59208673, -1.18261647,  0.53524064, -1.27412107,
          1.19152082, -0.04582379,  0.35265576, -0.89646596,
          0.22228963,  0.33457012],
        [-0.15813458,  3.16273745,  0.03422265, -1.12503984,
          1.07401234,  0.30729941,  0.71948992, -0.78518196,
         -1.4419849 , -2.62710247],
        [ 0.01523808,  0.99705485,  1.95069789, -1

In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
np.stack((a, b), axis=-1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [13]:
np.stack((a, b), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [17]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
np.stack(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])