# numpy.squeeze
https://numpy.org/doc/stable/reference/generated/numpy.squeeze.html#numpy-squeeze

numpy.squeeze(a, axis=None)
[source]

Remove axes of length one from a.

Parameters:

    aarray_like

        Input data.
    axisNone or int or tuple of ints, optional

        New in version 1.7.0.

        Selects a subset of the entries of length one in the shape. If an axis is selected with shape entry greater than one, an error is raised.

Returns:

    squeezed
    ndarray

        The input array, but with all or a subset of the dimensions of length 1 removed. This is always a itself or a view into a. Note that if all axes are squeezed, the result is a 0d array and not a scalar.

Raises:

    ValueError

        If axis is not None, and an axis being squeezed is not of length 1

See also

expand_dims

    The inverse operation, adding entries of length one
reshape

    Insert, remove, and combine dimensions, and resize existing ones



In [2]:
import numpy as np

In [7]:
x = np.array([[[0], [1], [2]]])
x

array([[[0],
        [1],
        [2]]])

In [9]:
np.squeeze(x)


array([0, 1, 2])

In [10]:
np.squeeze(x, axis=0)

array([[0],
       [1],
       [2]])

In [11]:
np.squeeze(x, axis=2)

array([[0, 1, 2]])

In [12]:
np.squeeze(x, axis=1)

ValueError: cannot select an axis to squeeze out which has size not equal to one

In [13]:
x = np.array([[1234]])

In [14]:
np.squeeze(x)

array(1234)

: 

In [3]:
x = np.array([1234])
np.squeeze(x)

array(1234)