# numpy.reshape
https://numpy.org/doc/stable/reference/generated/numpy.reshape.html

numpy.reshape(a, newshape, order='C')
[source]

Gives a new shape to an array without changing its data.

Parameters:

    a
    array_like

        Array to be reshaped.
    newshape
    int or tuple of ints

        The new shape should be compatible with the original shape. If an integer, then the result will be a 1-D array of that length. One shape dimension can be -1. In this case, the value is inferred from the length of the array and remaining dimensions.
    order
    {‘C’, ‘F’, ‘A’}, optional

        Read the elements of a using this index order, and place the elements into the reshaped array using this index order. ‘C’ means to read / write the elements using C-like index order, with the last axis index changing fastest, back to the first axis index changing slowest. ‘F’ means to read / write the elements using Fortran-like index order, with the first index changing fastest, and the last index changing slowest. Note that the ‘C’ and ‘F’ options take no account of the memory layout of the underlying array, and only refer to the order of indexing. ‘A’ means to read / write the elements in Fortran-like index order if a is Fortran contiguous in memory, C-like order otherwise.

Returns:

    reshaped_array
    ndarray

        This will be a new view object if possible; otherwise, it will be a copy. Note there is no guarantee of the memory layout (C- or Fortran- contiguous) of the returned array.

See also

ndarray.reshape

    Equivalent method.

Notes

It is not always possible to change the shape of an array without copying the data.

In [1]:
import numpy as np

In [3]:
a = np.arange(6).reshape((3, 2))
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [4]:
np.reshape(a, (2, 3))

array([[0, 1, 2],
       [3, 4, 5]])

In [5]:
a = np.array([[1,2,3], [4,5,6]])

np.reshape(a, 6)

array([1, 2, 3, 4, 5, 6])

In [6]:
np.reshape(a, (3,-1))  

array([[1, 2],
       [3, 4],
       [5, 6]])