# Introducing the tf.data module
https://www.coursera.org/learn/customising-models-tensorflow2/lecture/Fvs35/the-dataset-class

In [1]:
import tensorflow as tf

In [4]:
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6])

print(dataset)

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>


In [5]:
dataset = tf.data.Dataset.from_tensor_slices([[1, 2], [3, 4], [5, 6]])

print(dataset)

<_TensorSliceDataset element_spec=TensorSpec(shape=(2,), dtype=tf.int32, name=None)>


In [8]:
print(dataset.element_spec)

TensorSpec(shape=(2,), dtype=tf.int32, name=None)


In [6]:
for elem in dataset:
    print(elem)

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([3 4], shape=(2,), dtype=int32)
tf.Tensor([5 6], shape=(2,), dtype=int32)


In [7]:
for elem in dataset:
    print(elem.numpy())

[1 2]
[3 4]
[5 6]


In [11]:
dataset = tf.data.Dataset.from_tensor_slices(tf.random.uniform([128, 5]))

print(dataset)

print(dataset.element_spec)

for elem in dataset:
    print(elem.numpy())
    


<_TensorSliceDataset element_spec=TensorSpec(shape=(5,), dtype=tf.float32, name=None)>
TensorSpec(shape=(5,), dtype=tf.float32, name=None)
[0.97671604 0.24775982 0.9782491  0.441774   0.9333371 ]
[0.15153515 0.2051878  0.6445085  0.9990742  0.83473516]
[0.2684778  0.6639006  0.17938006 0.19401753 0.90578365]
[0.04800344 0.5628226  0.7029226  0.54060805 0.55441916]
[0.6626792  0.68105185 0.24827003 0.24161232 0.25828624]
[0.6186495  0.10073185 0.5456215  0.20277679 0.8314475 ]
[0.5539936  0.71308875 0.5926101  0.5666462  0.23467934]
[0.8730755  0.26361382 0.15390539 0.30298042 0.3541516 ]
[0.861318   0.53410983 0.68000877 0.29912305 0.6727431 ]
[0.89200497 0.19306695 0.5092137  0.40378428 0.5757803 ]
[0.28372037 0.04819608 0.3706633  0.23574245 0.51052177]
[0.32993484 0.15811002 0.13221169 0.17381918 0.66144884]
[0.59694195 0.8374299  0.21183741 0.4474262  0.35687578]
[0.26280546 0.23068213 0.88648415 0.5009624  0.18961227]
[0.57846177 0.4297521  0.32657826 0.6530131  0.97461617]
[0.882

In [14]:
dataset = tf.data.Dataset.from_tensor_slices(tf.random.uniform([2, 4, 4, 3]))

print(dataset)

print(dataset.element_spec)

for elem in dataset:
    print(elem.numpy())

<_TensorSliceDataset element_spec=TensorSpec(shape=(4, 4, 3), dtype=tf.float32, name=None)>
TensorSpec(shape=(4, 4, 3), dtype=tf.float32, name=None)
[[[0.43715382 0.03232062 0.89258385]
  [0.70050585 0.4801643  0.30984223]
  [0.78979325 0.7509413  0.9277272 ]
  [0.43609416 0.91013813 0.35309088]]

 [[0.579      0.11301732 0.25590765]
  [0.0921731  0.09029782 0.05120754]
  [0.14985132 0.93685913 0.11762381]
  [0.04061973 0.06091964 0.6893693 ]]

 [[0.12564528 0.19217229 0.4708873 ]
  [0.78996444 0.2675649  0.07052767]
  [0.6899154  0.6771004  0.45386446]
  [0.96259975 0.9700341  0.09852099]]

 [[0.79328597 0.6272267  0.20716977]
  [0.18695545 0.935815   0.23220861]
  [0.1719284  0.380723   0.89208925]
  [0.21618414 0.5051631  0.592566  ]]]
[[[0.9441042  0.55312526 0.32309544]
  [0.23408866 0.01603878 0.9426445 ]
  [0.8173772  0.31480718 0.614421  ]
  [0.51657355 0.4109577  0.45285797]]

 [[0.7815473  0.22027743 0.73796606]
  [0.82434666 0.7517551  0.5043632 ]
  [0.6082454  0.8983778  0.

In [20]:
dataset = tf.data.Dataset.from_tensor_slices(
    (
        tf.random.uniform([256, 4], minval=1, maxval=10, dtype=tf.int32),
        tf.random.normal([256])
    )
)

print(dataset.element_spec)

(TensorSpec(shape=(4,), dtype=tf.int32, name=None), TensorSpec(shape=(), dtype=tf.float32, name=None))


In [27]:
dataset = tf.data.Dataset.from_tensor_slices(
    (
        tf.random.uniform([2, 4, 4, 3], minval=0, maxval=256, dtype=tf.int32),
        tf.random.normal([2])
    )
)

#print(dataset)

#print(dataset.element_spec)

for elem in dataset:
    print(elem)

(<tf.Tensor: shape=(4, 4, 3), dtype=int32, numpy=
array([[[146, 151, 131],
        [  1,   4, 223],
        [134, 197, 169],
        [ 42,  17,  30]],

       [[134,  23,  58],
        [236,  90, 133],
        [184, 224, 139],
        [100, 125,  20]],

       [[236, 214,  59],
        [239, 164, 164],
        [213,  37, 250],
        [128,  55, 154]],

       [[122,   3, 159],
        [141, 212, 194],
        [167, 227, 254],
        [247, 143,  51]]], dtype=int32)>, <tf.Tensor: shape=(), dtype=float32, numpy=0.1649978905916214>)
(<tf.Tensor: shape=(4, 4, 3), dtype=int32, numpy=
array([[[202, 254, 162],
        [112, 156,  24],
        [ 47, 205, 216],
        [ 65, 221,  40]],

       [[196, 126, 228],
        [ 74, 182, 180],
        [255, 181,  16],
        [107, 194, 129]],

       [[178, 226, 109],
        [ 83, 156, 198],
        [171, 238,  18],
        [223, 230,  57]],

       [[ 77, 190,  66],
        [160,  92,  56],
        [ 49, 171, 246],
        [ 34,  34, 188]]], dtype

In [31]:
dataset = tf.data.Dataset.from_tensor_slices(
    (
        tf.random.uniform([2, 4, 4, 3], minval=0, maxval=256, dtype=tf.int32),
        tf.random.normal([2])
    )
)

#print(dataset)

#print(dataset.element_spec)

for elem in dataset.take(1):
    print(elem)

(<tf.Tensor: shape=(4, 4, 3), dtype=int32, numpy=
array([[[219, 204,  52],
        [251, 115, 203],
        [ 30, 210, 230],
        [ 53,  36,   0]],

       [[199,  72, 187],
        [119, 160,  96],
        [209,  63, 232],
        [130,  34, 242]],

       [[138,  53, 183],
        [251,  76,  10],
        [ 15,  95, 247],
        [ 74,  66,  64]],

       [[ 63, 242, 199],
        [157, 242,  23],
        [222,   3, 178],
        [184, 219,  44]]], dtype=int32)>, <tf.Tensor: shape=(), dtype=float32, numpy=-1.4467198848724365>)


In [32]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.cifar10.load_data()

dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))

print(dataset.element_spec)

(TensorSpec(shape=(32, 32, 3), dtype=tf.uint8, name=None), TensorSpec(shape=(1,), dtype=tf.uint8, name=None))


In [34]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

img_datagen = ImageDataGenerator(width_shift_range=0.2, horizontal_flip=True)
dataset = tf.data.Dataset.from_generator(img_datagen.flow, 
                                         args=[x_train, y_train],
                                         output_types=(tf.float32, tf.int32),
                                         output_shapes=([32, 32, 32, 3], [32, 1]))