# numpy.max
https://numpy.org/doc/stable/reference/generated/numpy.max.html

numpy.max(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
[source]

Return the maximum of an array or maximum along an axis.

Parameters:

    aarray_like

        Input data.
    axisNone or int or tuple of ints, optional

        Axis or axes along which to operate. By default, flattened input is used. If this is a tuple of ints, the maximum is selected over multiple axes, instead of a single axis or all the axes as before.
    outndarray, optional

        Alternative output array in which to place the result. Must be of the same shape and buffer length as the expected output. See Output type determination for more details.
    keepdimsbool, optional

        If this is set to True, the axes which are reduced are left in the result as dimensions with size one. With this option, the result will broadcast correctly against the input array.

        If the default value is passed, then keepdims will not be passed through to the max method of sub-classes of ndarray, however any non-default value will be. If the sub-class’ method does not implement keepdims any exceptions will be raised.
    initialscalar, optional

        The minimum value of an output element. Must be present to allow computation on empty slice. See reduce for details.
    wherearray_like of bool, optional

        Elements to compare for the maximum. See reduce for details.

Returns:

    max
    ndarray or scalar

        Maximum of a. If axis is None, the result is a scalar value. If axis is an int, the result is an array of dimension a.ndim - 1. If axis is a tuple, the result is an array of dimension a.ndim - len(axis).

See also

amin

    The minimum value of an array along a given axis, propagating any NaNs.
nanmax

    The maximum value of an array along a given axis, ignoring any NaNs.
maximum

    Element-wise maximum of two arrays, propagating any NaNs.
fmax

    Element-wise maximum of two arrays, ignoring any NaNs.
argmax

    Return the indices of the maximum values.
nanmin, minimum, fmin

Notes

NaN values are propagated, that is if at least one item is NaN, the corresponding max value will be NaN as well. To ignore NaN values (MATLAB behavior), please use nanmax.

Don’t use max for element-wise comparison of 2 arrays; when a.shape[0] is 2, maximum(a[0], a[1]) is faster than max(a, axis=0).

In [1]:
import numpy as np

In [2]:
a = np.arange(4).reshape((2,2))

a

array([[0, 1],
       [2, 3]])

In [3]:
np.max(a) 

np.int64(3)

In [6]:
np.max(a, axis=0)   # Maxima along the first axis

array([2, 3])

In [8]:
b = np.array([[1, 2],
              [0, 3]])
np.max(b, axis=0, keepdims=True)   # Maxima along the first axis

array([[1, 3]])

In [4]:
np.max(a, axis=1)

array([1, 3])

In [5]:
np.max(a, axis=1, keepdims=True)

array([[1],
       [3]])

In [9]:
np.max(a, where=[False, True], initial=-1, axis=0)

array([-1,  3])

In [10]:
b = np.arange(5, dtype=float)

b[2] = np.nan

np.max(b)

np.float64(nan)

In [11]:
np.max(b, where=~np.isnan(b), initial=-1)
4.0

4.0

In [12]:
np.max([[-50], [10]], axis=-1, initial=0)

array([ 0, 10])

In [13]:
np.max([5], initial=6)

np.int64(6)

In [14]:
max([5], default=6)

5