# numpy.sum
https://numpy.org/doc/stable/reference/generated/numpy.sum.html

numpy.sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
[source]

Sum of array elements over a given axis.

Parameters:

    aarray_like

        Elements to sum.
    axisNone or int or tuple of ints, optional

        Axis or axes along which a sum is performed. The default, axis=None, will sum all of the elements of the input array. If axis is negative it counts from the last to the first axis.

        New in version 1.7.0.

        If axis is a tuple of ints, a sum is performed on all of the axes specified in the tuple instead of a single axis or all the axes as before.
    dtypedtype, optional

        The type of the returned array and of the accumulator in which the elements are summed. The dtype of a is used by default unless a has an integer dtype of less precision than the default platform integer. In that case, if a is signed then the platform integer is used while if a is unsigned then an unsigned integer of the same precision as the platform integer is used.
    outndarray, optional

        Alternative output array in which to place the result. It must have the same shape as the expected output, but the type of the output values will be cast if necessary.
    keepdimsbool, optional

        If this is set to True, the axes which are reduced are left in the result as dimensions with size one. With this option, the result will broadcast correctly against the input array.

        If the default value is passed, then keepdims will not be passed through to the sum method of sub-classes of ndarray, however any non-default value will be. If the sub-class’ method does not implement keepdims any exceptions will be raised.
    initialscalar, optional

        Starting value for the sum. See reduce for details.

        New in version 1.15.0.
    wherearray_like of bool, optional

        Elements to include in the sum. See reduce for details.

        New in version 1.17.0.

Returns:

    sum_along_axis
    ndarray

        An array with the same shape as a, with the specified axis removed. If a is a 0-d array, or if axis is None, a scalar is returned. If an output array is specified, a reference to out is returned.

See also

ndarray.sum

    Equivalent method.
add

    numpy.add.reduce equivalent function.
cumsum

    Cumulative sum of array elements.
mean, average

Notes

Arithmetic is modular when using integer types, and no error is raised on overflow.

In [2]:
import numpy as np

In [3]:
np.sum([])

0.0

In [4]:
np.sum([0.5, 1.5])

2.0

In [5]:
np.sum([0.5, 0.7, 0.2, 1.5], dtype=np.int32)

1

In [6]:
np.sum([[0, 1], [0, 5]])

6

In [7]:
np.sum([[0, 1], [0, 5]], axis=0)

array([0, 6])

In [8]:
np.sum([[0, 1], [0, 5]], axis=1)

array([1, 5])

In [9]:
np.sum([[0, 1], [np.nan, 5]], where=[False, True], axis=1)

array([1., 5.])

In [12]:
np.sum([[0, 1], [np.nan, 5]], where=[False, True], axis=0)

array([0., 6.])

In [13]:
np.sum([10], initial=5)

15

In [14]:
np.sum([10, 20, 30], initial=5)

65

In [17]:
np.sum([[10, 20, 30], [1,2, 3]], initial=5, axis=1)

array([65, 11])

In [18]:
np.sum([[10, 20, 30], [1,2, 3]], initial=5, axis=0)

array([16, 27, 38])