In [19]:
import tensorflow as tf
import numpy as np

In [2]:
y_pred = [[0.1,0.6,0.3] , [0.2,0.7,0.1], [0.1, 0.5,0.4], [0.4,0.4,0.2]]
y_pred

[[0.1, 0.6, 0.3], [0.2, 0.7, 0.1], [0.1, 0.5, 0.4], [0.4, 0.4, 0.2]]

In [3]:
y_pred_class = tf.math.argmax(y_pred, axis=-1)
y_pred_class

2025-03-27 11:59:11.005649: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 1, 1, 0])>

In [ ]:
y_pred_class = tf.cast(y_pred_class, tf.float32) 

In [5]:
y_pred_class

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 1., 1., 0.], dtype=float32)>

In [ ]:
y_true = [0,1,2,0]

In [7]:
y_true = tf.cast(y_true, tf.float32) 
y_true

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 1., 2., 0.], dtype=float32)>

In [8]:
matches_true_pred  = tf.equal(y_true, y_pred_class)
matches_true_pred

<tf.Tensor: shape=(4,), dtype=bool, numpy=array([False,  True, False,  True])>

In [9]:
matches_true_pred = tf.cast(matches_true_pred , tf.float32) 
matches_true_pred

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 1., 0., 1.], dtype=float32)>

In [18]:
true_labels_1 = [0,-1,2,0]
true_labels_1 = tf.cast(true_labels_1, tf.float32)
mask = tf.math.not_equal(true_labels_1, -1)
mask

<tf.Tensor: shape=(4,), dtype=bool, numpy=array([ True, False,  True,  True])>

In [11]:
mask = tf.cast(mask, tf.float32) 
mask

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 1., 1., 1.], dtype=float32)>

In [12]:
matches_true_pred *= mask
matches_true_pred

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 1., 0., 1.], dtype=float32)>

In [13]:
masked_acc = tf.reduce_sum(matches_true_pred) / tf.reduce_sum(mask)
masked_acc

<tf.Tensor: shape=(), dtype=float32, numpy=0.5>

In [22]:
x = tf.expand_dims(np.array([545, 467, 896]), axis = 0)
x

<tf.Tensor: shape=(1, 3), dtype=int64, numpy=array([[545, 467, 896]])>

In [23]:
x_padded = tf.expand_dims(np.array([545, 467, 896, 0, 0, 0]), axis = 0)
x_padded

<tf.Tensor: shape=(1, 6), dtype=int64, numpy=array([[545, 467, 896,   0,   0,   0]])>