# numpy.mean
https://numpy.org/devdocs/reference/generated/numpy.mean.html#numpy-mean

numpy.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>, *, where=<no value>)
[source]

Compute the arithmetic mean along the specified axis.

Returns the average of the array elements. The average is taken over the flattened array by default, otherwise over the specified axis. float64 intermediate and return values are used for integer inputs.

Parameters:

    aarray_like

        Array containing numbers whose mean is desired. If a is not an array, a conversion is attempted.
    axisNone or int or tuple of ints, optional

        Axis or axes along which the means are computed. The default is to compute the mean of the flattened array.

        New in version 1.7.0.

        If this is a tuple of ints, a mean is performed over multiple axes, instead of a single axis or all the axes as before.
    dtypedata-type, optional

        Type to use in computing the mean. For integer inputs, the default is float64; for floating point inputs, it is the same as the input dtype.
    outndarray, optional

        Alternate output array in which to place the result. The default is None; if provided, it must have the same shape as the expected output, but the type will be cast if necessary. See Output type determination for more details. See Output type determination for more details.
    keepdimsbool, optional

        If this is set to True, the axes which are reduced are left in the result as dimensions with size one. With this option, the result will broadcast correctly against the input array.

        If the default value is passed, then keepdims will not be passed through to the mean method of sub-classes of ndarray, however any non-default value will be. If the sub-class’ method does not implement keepdims any exceptions will be raised.
    wherearray_like of bool, optional

        Elements to include in the mean. See reduce for details.

        New in version 1.20.0.

Returns:

    m
    ndarray, see dtype parameter above

        If out=None, returns a new array containing the mean values, otherwise a reference to the output array is returned.

See also

average

    Weighted average
std, var, nanmean, nanstd, nanvar

Notes

The arithmetic mean is the sum of the elements along the axis divided by the number of elements.

Note that for floating-point input, the mean is computed using the same precision the input has. Depending on the input data, this can cause the results to be inaccurate, especially for float32 (see example below). Specifying a higher-precision accumulator using the dtype keyword can alleviate this issue.

By default, float16 results are computed using float32 intermediates for extra precision.

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2], [3, 4]])

np.mean(a)

2.5

In [3]:
np.mean(a, axis=0)

array([2., 3.])

In [4]:
np.mean(a, axis=1)

array([1.5, 3.5])

In [3]:
np.mean(a, where=[[True], [False]])

1.5

In [4]:
np.mean(a, where=[[True], [True]])

2.5

In [5]:
np.mean(a, where=[[False], [True]])

3.5

In [6]:
np.mean(a, where=[[False], [False]])

d:\tutorials\python\python-tutorials\tutorial\.venv\Lib\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
d:\tutorials\python\python-tutorials\tutorial\.venv\Lib\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)


nan

In [7]:
b = np.array([[[1, 2, 3], 
               [4, 5, 6]], 
              
              [[7, 8, 9], 
               [10, 11, 12]]
             ])

In [10]:
np.mean(b, axis=None)

6.5

In [8]:
np.mean(b, axis=0)

array([[4., 5., 6.],
       [7., 8., 9.]])

In [9]:
np.mean(b, axis=1)

array([[ 2.5,  3.5,  4.5],
       [ 8.5,  9.5, 10.5]])

In [11]:
np.mean(b, axis=2)

array([[ 2.,  5.],
       [ 8., 11.]])

In [ ]:
c = np.array([[[[1 2, 3], 
               [4, 5, 6],              
               [7, 8, 9]], 
              [[10, 11, 12],
               [13, 14, 15],
               [16, 17, 18]],
              [[19, 20, 21],
               [22, 23, 24],
               [25, 26, 27]]
             ]])

In [22]:
d = np.arange(18).reshape((2, 3, 3, 1))

In [20]:
d

array([[[[ 0],
         [ 1],
         [ 2]],

        [[ 3],
         [ 4],
         [ 5]],

        [[ 6],
         [ 7],
         [ 8]]],


       [[[ 9],
         [10],
         [11]],

        [[12],
         [13],
         [14]],

        [[15],
         [16],
         [17]]],


       [[[18],
         [19],
         [20]],

        [[21],
         [22],
         [23]],

        [[24],
         [25],
         [26]]]])

In [23]:
d.shape

(2, 3, 3, 1)

In [24]:
np.mean(d, axis=0)

array([[[ 4.5],
        [ 5.5],
        [ 6.5]],

       [[ 7.5],
        [ 8.5],
        [ 9.5]],

       [[10.5],
        [11.5],
        [12.5]]])

In [25]:
d.mean(axis=0)

array([[[ 4.5],
        [ 5.5],
        [ 6.5]],

       [[ 7.5],
        [ 8.5],
        [ 9.5]],

       [[10.5],
        [11.5],
        [12.5]]])

In [28]:
e = np.arange(96).reshape((2, 4, 4, 3))
e

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44],
         [45, 46, 47]]],


       [[[48, 49, 50],
         [51, 52, 53],
         [54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80],
         [81, 82, 83]],

        [[84, 85, 86],
         [87, 88, 89],
         [90, 91, 92],
         [93, 94, 95]]]])

In [31]:
e_mean = e.mean(axis=3, keepdims=True)
e_mean

array([[[[ 1.],
         [ 4.],
         [ 7.],
         [10.]],

        [[13.],
         [16.],
         [19.],
         [22.]],

        [[25.],
         [28.],
         [31.],
         [34.]],

        [[37.],
         [40.],
         [43.],
         [46.]]],


       [[[49.],
         [52.],
         [55.],
         [58.]],

        [[61.],
         [64.],
         [67.],
         [70.]],

        [[73.],
         [76.],
         [79.],
         [82.]],

        [[85.],
         [88.],
         [91.],
         [94.]]]])

In [32]:
e_mean.shape

(2, 4, 4, 1)

In [35]:
e_mean = np.mean(e, axis=3, keepdims=True)
e_mean

array([[[[ 1.],
         [ 4.],
         [ 7.],
         [10.]],

        [[13.],
         [16.],
         [19.],
         [22.]],

        [[25.],
         [28.],
         [31.],
         [34.]],

        [[37.],
         [40.],
         [43.],
         [46.]]],


       [[[49.],
         [52.],
         [55.],
         [58.]],

        [[61.],
         [64.],
         [67.],
         [70.]],

        [[73.],
         [76.],
         [79.],
         [82.]],

        [[85.],
         [88.],
         [91.],
         [94.]]]])

In [36]:
e_mean.shape

(2, 4, 4, 1)

In [37]:
e_mean.mean(axis=0)

array([[[25.],
        [28.],
        [31.],
        [34.]],

       [[37.],
        [40.],
        [43.],
        [46.]],

       [[49.],
        [52.],
        [55.],
        [58.]],

       [[61.],
        [64.],
        [67.],
        [70.]]])