# numpy.dot
https://numpy.org/doc/stable/reference/generated/numpy.dot.html#numpy.dot

numpy.dot(a, b, out=None)

Dot product of two arrays. Specifically,

    If both a and b are 1-D arrays, it is inner product of vectors (without complex conjugation).

    If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.

    If either a or b is 0-D (scalar), it is equivalent to multiply and using numpy.multiply(a, b) or a * b is preferred.

    If a is an N-D array and b is a 1-D array, it is a sum product over the last axis of a and b.

    If a is an N-D array and b is an M-D array (where M>=2), it is a sum product over the last axis of a and the second-to-last axis of b:

    dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])

It uses an optimized BLAS library when possible (see numpy.linalg).

Parameters:

    a
    array_like

        First argument.
    b
    array_like

        Second argument.
    out
    ndarray, optional

        Output argument. This must have the exact kind that would be returned if it was not used. In particular, it must have the right type, must be C-contiguous, and its dtype must be the dtype that would be returned for dot(a,b). This is a performance feature. Therefore, if these conditions are not met, an exception is raised, instead of attempting to be flexible.

Returns:

    output
    ndarray

        Returns the dot product of a and b. If a and b are both scalars or both 1-D arrays then a scalar is returned; otherwise an array is returned. If out is given, then it is returned.

Raises:

    ValueError

        If the last dimension of a is not the same size as the second-to-last dimension of b.

See also

vdot

    Complex-conjugating dot product.
vecdot

    Vector dot product of two arrays.
tensordot

    Sum products over arbitrary axes.
einsum

    Einstein summation convention.
matmul

    ‘@’ operator as method with out parameter.
linalg.multi_dot

    Chained dot product.



In [1]:
import numpy as np

In [2]:
np.dot(3, 4)

np.int64(12)

In [3]:
print(np.dot(3, 4))

12


In [4]:
np.dot([2j, 3j], [2j, 3j])

np.complex128(-13+0j)

In [5]:
print(np.dot([2j, 3j], [2j, 3j]))

(-13+0j)


In [6]:
a = [[1, 0], 
     [0, 1]]

b = [[4, 1], 
     [2, 2]]

np.dot(a, b)

array([[4, 1],
       [2, 2]])

In [7]:
a = np.arange(3*4*5*6).reshape((3,4,5,6))
print(a)

[[[[  0   1   2   3   4   5]
   [  6   7   8   9  10  11]
   [ 12  13  14  15  16  17]
   [ 18  19  20  21  22  23]
   [ 24  25  26  27  28  29]]

  [[ 30  31  32  33  34  35]
   [ 36  37  38  39  40  41]
   [ 42  43  44  45  46  47]
   [ 48  49  50  51  52  53]
   [ 54  55  56  57  58  59]]

  [[ 60  61  62  63  64  65]
   [ 66  67  68  69  70  71]
   [ 72  73  74  75  76  77]
   [ 78  79  80  81  82  83]
   [ 84  85  86  87  88  89]]

  [[ 90  91  92  93  94  95]
   [ 96  97  98  99 100 101]
   [102 103 104 105 106 107]
   [108 109 110 111 112 113]
   [114 115 116 117 118 119]]]


 [[[120 121 122 123 124 125]
   [126 127 128 129 130 131]
   [132 133 134 135 136 137]
   [138 139 140 141 142 143]
   [144 145 146 147 148 149]]

  [[150 151 152 153 154 155]
   [156 157 158 159 160 161]
   [162 163 164 165 166 167]
   [168 169 170 171 172 173]
   [174 175 176 177 178 179]]

  [[180 181 182 183 184 185]
   [186 187 188 189 190 191]
   [192 193 194 195 196 197]
   [198 199 200 201 202 203]


In [8]:
b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3))
print(b)

[[[[359 358 357]
   [356 355 354]
   [353 352 351]
   [350 349 348]
   [347 346 345]
   [344 343 342]]

  [[341 340 339]
   [338 337 336]
   [335 334 333]
   [332 331 330]
   [329 328 327]
   [326 325 324]]

  [[323 322 321]
   [320 319 318]
   [317 316 315]
   [314 313 312]
   [311 310 309]
   [308 307 306]]

  [[305 304 303]
   [302 301 300]
   [299 298 297]
   [296 295 294]
   [293 292 291]
   [290 289 288]]]


 [[[287 286 285]
   [284 283 282]
   [281 280 279]
   [278 277 276]
   [275 274 273]
   [272 271 270]]

  [[269 268 267]
   [266 265 264]
   [263 262 261]
   [260 259 258]
   [257 256 255]
   [254 253 252]]

  [[251 250 249]
   [248 247 246]
   [245 244 243]
   [242 241 240]
   [239 238 237]
   [236 235 234]]

  [[233 232 231]
   [230 229 228]
   [227 226 225]
   [224 223 222]
   [221 220 219]
   [218 217 216]]]


 [[[215 214 213]
   [212 211 210]
   [209 208 207]
   [206 205 204]
   [203 202 201]
   [200 199 198]]

  [[197 196 195]
   [194 193 192]
   [191 190 189]
   [188 1

In [9]:
np.dot(a, b)

array([[[[[[  5220,   5205,   5190],
           [  4950,   4935,   4920],
           [  4680,   4665,   4650],
           [  4410,   4395,   4380]],

          [[  4140,   4125,   4110],
           [  3870,   3855,   3840],
           [  3600,   3585,   3570],
           [  3330,   3315,   3300]],

          [[  3060,   3045,   3030],
           [  2790,   2775,   2760],
           [  2520,   2505,   2490],
           [  2250,   2235,   2220]],

          [[  1980,   1965,   1950],
           [  1710,   1695,   1680],
           [  1440,   1425,   1410],
           [  1170,   1155,   1140]],

          [[   900,    885,    870],
           [   630,    615,    600],
           [   360,    345,    330],
           [    90,     75,     60]]],


         [[[ 17874,  17823,  17772],
           [ 16956,  16905,  16854],
           [ 16038,  15987,  15936],
           [ 15120,  15069,  15018]],

          [[ 14202,  14151,  14100],
           [ 13284,  13233,  13182],
           [ 12366,  123